plugins {
    id 'com.android.application'
}

android {
    namespace 'de.brandenburg.anglertrainer'
    compileSdk 36

    defaultConfig {
        applicationId "de.brandenburg.anglertrainer"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
}
